declare module "rc-drawer"
declare module "*.png"
declare module "*.jpg"
declare module "*.svg"
declare module "*.gif"
declare module "*.webp"
declare module "react-particles-js"
declare module "react-netlify-form"